// Generated by CoffeeScript 1.9.0

/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
'use strict';
var Backend, Cache, Promise, expiresAt, extend, isExpired, optionalOpts, toPromise;

extend = require('lodash').extend;

Promise = require('bluebird');

Backend = require('./backend');

toPromise = function(val) {
  if ('function' === typeof val) {
    return Promise.resolve(val());
  } else {
    return Promise.resolve(val);
  }
};

expiresAt = function(seconds) {
  if (seconds === 0) {
    return 0;
  } else {
    return Date.now() + parseInt(seconds, 10) * 1000;
  }
};

isExpired = function(expires) {
  if (expires === 0) {
    return false;
  }
  return Date.now() > new Date(expires).getTime();
};

optionalOpts = function(opts, cb) {
  if ((cb == null) && 'function' === typeof opts) {
    return {
      cb: opts,
      opts: null
    };
  } else {
    return {
      cb: cb,
      opts: opts
    };
  }
};

Cache = (function() {
  function Cache(_arg) {
    var backend, defaults, name;
    backend = _arg.backend, defaults = _arg.defaults, name = _arg.name;
    this.defaults = {
      freshFor: 0,
      expire: 0
    };
    this.name = name || 'default';
    this.prefix = this.name + ":";
    this.staleOrPending = {};
    this.setDefaults(defaults);
    this.setBackend(backend);
  }

  Cache.prototype.applyPrefix = function(key) {
    return "" + this.prefix + key;
  };

  Cache.prototype.setDefaults = function(defaults) {
    return this.defaults = this.prepareOptions(defaults);
  };

  Cache.prototype.setBackend = function(backendOptions) {
    backendOptions = 'string' === typeof backendOptions ? {
      type: backendOptions
    } : backendOptions != null ? backendOptions : {};
    this.end();
    return this.backend = Backend.create(backendOptions);
  };

  Cache.prototype.end = function() {
    var _ref;
    if (((_ref = this.backend) != null ? _ref.end : void 0) != null) {
      return this.backend.end();
    }
  };

  Cache.prototype.prepareOptions = function(options) {
    return extend({}, this.defaults, options);
  };

  Cache.prototype.set = function(key, val, opts, cb) {
    var _ref;
    _ref = optionalOpts(opts, cb), cb = _ref.cb, opts = _ref.opts;
    key = this.applyPrefix(key);
    opts = this.prepareOptions(opts);
    return toPromise(val).then((function(_this) {
      return function(resolvedValue) {
        return _this.backend.set(key, {
          b: expiresAt(opts.freshFor),
          d: resolvedValue
        }, opts);
      };
    })(this)).nodeify(cb);
  };

  Cache.prototype.getWrapped = function(key) {
    return this.backend.get(key);
  };

  Cache.prototype.get = function(rawKey, cb) {
    var key;
    key = this.applyPrefix(rawKey);
    return this.getWrapped(key).then(function(wrappedValue) {
      var _ref;
      return (_ref = wrappedValue != null ? wrappedValue.d : void 0) != null ? _ref : null;
    }).nodeify(cb);
  };

  Cache.prototype.getOrElse = function(rawKey, val, opts, cb) {
    var handleError, key, refreshValue, verifyFreshness, _ref;
    key = this.applyPrefix(rawKey);
    _ref = optionalOpts(opts, cb), cb = _ref.cb, opts = _ref.opts;
    opts = this.prepareOptions(opts);
    refreshValue = (function(_this) {
      return function() {
        var generatedValue;
        generatedValue = toPromise(val);
        return _this.set(rawKey, generatedValue, opts).then(function(rawValue) {
          var _ref1;
          delete _this.staleOrPending[key];
          return (_ref1 = rawValue != null ? rawValue.d : void 0) != null ? _ref1 : null;
        }, function(err) {
          delete _this.staleOrPending[key];
          return generatedValue != null ? generatedValue : null;
        });
      };
    })(this);
    verifyFreshness = (function(_this) {
      return function(wrappedValue) {
        var expired, hit, loadingNewValue, _ref1;
        hit = wrappedValue != null;
        expired = isExpired(wrappedValue != null ? wrappedValue.b : void 0);
        loadingNewValue = _this.staleOrPending[key] != null;
        if ((!hit || expired) && !loadingNewValue) {
          _this.staleOrPending[key] = refreshValue();
        }
        return (_ref1 = wrappedValue != null ? wrappedValue.d : void 0) != null ? _ref1 : _this.staleOrPending[key];
      };
    })(this);
    handleError = function(error) {
      return null;
    };
    return this.getWrapped(key)["catch"](handleError).then(verifyFreshness).nodeify(cb);
  };

  return Cache;

})();

module.exports = Cache;
