/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Backend, Cache, expiresAt, extend, isExpired, optionalOpts, Q, toPromise;
  extend = require('underscore').extend;
  Q = require('q');
  Backend = require('./backend');
  toPromise = function (val) {
    if ('function' === typeof val) {
      return Q(val());
    } else {
      return Q(val);
    }
  };
  expiresAt = function (seconds) {
    if (seconds === 0) {
      return 0;
    } else {
      return Date.now() + parseInt(seconds, 10) * 1e3;
    }
  };
  isExpired = function (expires) {
    if (expires === 0)
      return false;
    return Date.now() > new Date(expires).getTime();
  };
  optionalOpts = function (opts, cb) {
    if (!(null != cb) && 'function' === typeof opts) {
      return {
        cb: opts,
        opts: null
      };
    } else {
      return {
        cb: cb,
        opts: opts
      };
    }
  };
  Cache = function () {
    function Cache(param$) {
      var backend, cache$, defaults, name;
      {
        cache$ = param$;
        backend = cache$.backend;
        defaults = cache$.defaults;
        name = cache$.name;
      }
      this.defaults = {
        freshFor: 0,
        expire: 0
      };
      this.name = name || 'default';
      this.prefix = '' + this.name + ':';
      this.staleOrPending = {};
      this.setDefaults(defaults);
      this.setBackend(backend);
    }
    Cache.prototype.applyPrefix = function (key) {
      return '' + this.prefix + key;
    };
    Cache.prototype.setDefaults = function (defaults) {
      return this.defaults = this.prepareOptions(defaults);
    };
    Cache.prototype.setBackend = function (backendOptions) {
      backendOptions = 'string' === typeof backendOptions ? { type: backendOptions } : null != backendOptions ? backendOptions : {};
      this.end();
      return this.backend = Backend.create(backendOptions);
    };
    Cache.prototype.end = function () {
      if (null != (null != this.backend ? this.backend.end : void 0))
        return this.backend.end();
    };
    Cache.prototype.prepareOptions = function (options) {
      return extend({}, this.defaults, options);
    };
    Cache.prototype.set = function (key, val, opts, cb) {
      var backend, cache$;
      cache$ = optionalOpts(opts, cb);
      cb = cache$.cb;
      opts = cache$.opts;
      key = this.applyPrefix(key);
      backend = this.backend;
      opts = this.prepareOptions(opts);
      return toPromise(val).then(function (resolvedValue) {
        var wrappedValue;
        wrappedValue = {
          b: expiresAt(opts.freshFor),
          d: resolvedValue
        };
        return Q.npost(backend, 'set', [
          key,
          wrappedValue,
          opts
        ]);
      }).nodeify(cb);
    };
    Cache.prototype.getWrapped = function (key) {
      return Q.npost(this.backend, 'get', [key]);
    };
    Cache.prototype.get = function (rawKey, cb) {
      var key;
      key = this.applyPrefix(rawKey);
      return this.getWrapped(key).then(function (wrappedValue) {
        return null != (null != wrappedValue ? wrappedValue.d : void 0) ? null != wrappedValue ? wrappedValue.d : void 0 : null;
      }).nodeify(cb);
    };
    Cache.prototype.getOrElse = function (rawKey, val, opts, cb) {
      var cache$, handleError, key, refreshValue, verifyFreshness;
      key = this.applyPrefix(rawKey);
      cache$ = optionalOpts(opts, cb);
      cb = cache$.cb;
      opts = cache$.opts;
      opts = this.prepareOptions(opts);
      refreshValue = function (this$) {
        return function () {
          var generatedValue;
          generatedValue = 'function' === typeof val ? val() : val;
          return this$.set(rawKey, generatedValue, opts).then(function (this$1) {
            return function (rawValue) {
              delete this$1.staleOrPending[key];
              return null != (null != rawValue ? rawValue.d : void 0) ? null != rawValue ? rawValue.d : void 0 : null;
            };
          }(this$), function (this$1) {
            return function (err) {
              delete this$1.staleOrPending[key];
              return null != generatedValue ? generatedValue : null;
            };
          }(this$));
        };
      }(this);
      verifyFreshness = function (this$) {
        return function (wrappedValue) {
          var expired, hit, loadingNewValue;
          hit = null != wrappedValue;
          expired = isExpired(null != wrappedValue ? wrappedValue.b : void 0);
          loadingNewValue = null != this$.staleOrPending[key];
          if ((!hit || expired) && !loadingNewValue)
            this$.staleOrPending[key] = refreshValue();
          return null != (null != wrappedValue ? wrappedValue.d : void 0) ? null != wrappedValue ? wrappedValue.d : void 0 : this$.staleOrPending[key];
        };
      }(this);
      handleError = function (error) {
        return null;
      };
      return this.getWrapped(key)['catch'](handleError).then(verifyFreshness).nodeify(cb);
    };
    return Cache;
  }();
  module.exports = Cache;
}.call(this);
